# Generated by Django 4.1.7 on 2023-03-29 07:37

from django.db import migrations, models
import django.db.models.deletion
import post_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0011_alter_post_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=post_image.models.post_image_directory_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
