# Generated by Django 4.1.7 on 2023-03-28 09:09

from django.db import migrations, models
import registrationprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='validation_code',
            field=models.CharField(default=registrationprofile.models.code_generator, max_length=10),
        ),
    ]
