# Generated by Django 4.1.7 on 2023-03-28 09:35

from django.db import migrations, models
import registrationprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationprofile', '0004_alter_registrationprofile_validation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='validation_code',
            field=models.TextField(default=registrationprofile.models.code_generator, help_text='random code used for registration and for password reset', max_length=15),
        ),
    ]
