# Generated by Django 4.1.7 on 2023-03-28 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrationprofile', '0005_alter_registrationprofile_validation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
