# Generated by Django 4.1.7 on 2023-03-28 08:45

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar_user_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged_in_user_followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logged_in_user_following',
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='things_user_likes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
