# Generated by Django 4.1.7 on 2023-03-28 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_logged_in_user_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in_user_followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='logged_in_user_following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
