# Generated by Django 4.1.7 on 2023-03-29 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_logged_in_user_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_of_friends',
            field=models.ManyToManyField(related_name='befriended_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], max_length=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_fr', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_fr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='logged_in_user_received_fr',
            field=models.ManyToManyField(through='user.FriendRequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
